#!/bin/bash

ROUTE="ws://localhost:8080/hypervisor/ws/stages/$1/tests/$2"
echo $ROUTE

wscat --connect $ROUTE \
     --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjEwODA2ODQsInBhc3N3b3JkIjoiJDJhJDEyJC9EbHVwOVVpVUwwano5cnpHNWl3Y08vVnVnLzF0Q2pXWFdxZGN0dmVpem1CcFNONXlUVUY2IiwidXNlcm5hbWUiOiJzdW5zaGluZSJ9.C0cP08xgcQoz3AisEbFkipSxY45agw0-ZzlCxMwcdN4" 